name: Deploy Content to law-sentinel-sdi-hub-ae-001 [f09949e9-2f6a-40cd-832e-556447810236]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-f09949e9-2f6a-40cd-832e-556447810236.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ sentineltest ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-f09949e9-2f6a-40cd-832e-556447810236.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'rg-sentinel-sdi-hub-ae-001'
      workspaceName: 'law-sentinel-sdi-hub-ae-001'
      workspaceId: 'fb8a645c-f06d-47fd-a0de-37e89cbbc354'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule'
      branch: 'sentineltest'
      sourceControlId: 'f09949e9-2f6a-40cd-832e-556447810236'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_f09949e92f6a40cd832e556447810236 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_f09949e92f6a40cd832e556447810236 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f09949e92f6a40cd832e556447810236 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_f09949e92f6a40cd832e556447810236 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_f09949e92f6a40cd832e556447810236 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f09949e92f6a40cd832e556447810236 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_f09949e92f6a40cd832e556447810236 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_f09949e92f6a40cd832e556447810236 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f09949e92f6a40cd832e556447810236 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-f09949e9-2f6a-40cd-832e-556447810236.ps1